api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from api.views import NEViewSet, ListVendors, ListModels, ListTasks, NEDetail, ArchiveConfig, ConfigDiff, \
    IsPPPoEIAConfigured, ConfigSearch

router = routers.DefaultRouter()
router.register(r'ne_list', NEViewSet, 'ne_list')
router.register(r'vendors', ListVendors, 'vendors')
router.register(r'models', ListModels, 'models')
router.register(r'tasks', ListTasks, 'tasks')
# router.register(r'ne_detail', NEDetail, 'ne_detail')


urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'ne_detail/(?P<pk>[0-9]+)/$', NEDetail.as_view()),
    url(r'get_archived_config/(?P<pk>[0-9]+)/$', ArchiveConfig.as_view()),
    url(r'get_config_diff/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ConfigDiff.as_view()),
    url(r'is_pppoe_ia_configured/(?P<ip>.+)/$', IsPPPoEIAConfigured.as_view()),
    url(r'config_search/(?P<ip>.+)/(?P<search>.+)$', ConfigSearch.as_view()),
    url(r'^', include(router.urls))

]

lna/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

lna/users/models.py
from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

net/models.py
from django.db import models
from django.utils import timezone
from argus.models import ASTU
from django.contrib.postgres.fields import JSONField
from netfields import InetAddressField, NetManager

# Create your models here.


class Scripts(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(max_length=10000)
    class_name = models.CharField(max_length=255)
    possible_vendor = models.CharField(max_length=255)
    possible_model = models.CharField(max_length=255)
    is_hidden = models.BooleanField(default=False)

    class Meta:
        ordering = ('name', )


class Job(models.Model):
    name = models.CharField(max_length=255)
    status = models.CharField(max_length=255, null=True, blank=True)
    created = models.DateTimeField(default=timezone.now)
    completed = models.DateTimeField(null=True)
    celery_id = models.CharField(max_length=255)
    script = models.ForeignKey(Scripts, on_delete=models.CASCADE, null=True)
    ne_ids = models.ManyToManyField(ASTU)
    meta = JSONField(default='')

    class Meta:
        ordering = ('-created', )

    def __str__(self):
        return self.name


class JobResult(models.Model):
    job_id = models.ForeignKey(Job, on_delete=models.CASCADE)
    result = models.TextField(max_length=10000)


# Login/Pass/Enable credentials
class Credentials(models.Model):
    login = models.CharField(max_length=512, default='')
    passw = models.CharField(max_length=512, default='')
    enable_password = models.CharField(max_length=512, default='')
    snmp_community = models.CharField(max_length=512, default='')
    comment = models.CharField(max_length=512, default='')

    class Meta:
        ordering = ('id', )

    def __str__(self):
        return "Credentials: " + self.login + " / " + self.passw


# proven-info model class
class Equipment(models.Model):
    hostname = models.CharField(max_length=512, null=True, default=None)
    vendor = models.CharField(max_length=512, null=True, default=None)
    model = models.CharField(max_length=512, null=True, default=None)
    # ne_ip = models.GenericIPAddressField(protocol='IPv4', db_index=True, unique=True)
    ne_ip = InetAddressField(db_index=True, unique=True)
    credentials = models.ForeignKey(Credentials, on_delete=models.CASCADE, null=True)
    sw_version = models.CharField(max_length=512, null=True, default=None)  # software version
    telnet_port_open = models.BooleanField(default=False)
    current_config = models.TextField()

    objects = NetManager()

    def __str__(self):
        return "Equipment object with IP: " + str(self.ne_ip)


class EquipmentSuggestCredentials(models.Model):
    equipment_id = models.ForeignKey(Equipment, on_delete=models.CASCADE, null=True)  # Equipment foreign key
    credentials_id = models.ForeignKey(Credentials, on_delete=models.CASCADE, null=True)  # Credentials FK
    # True if was unsuccessful attempt to login equipment with provided credentials
    was_checked = models.BooleanField(default=False)

    class Meta:
        ordering = ('equipment_id', )


class EquipmentConfig(models.Model):
    equipment_id = models.ForeignKey(Equipment, on_delete=models.CASCADE, null=True)  # Equipment foreign key
    updated = models.DateTimeField(auto_now_add=True)  # when config was updated
    config = models.TextField()  # subj

    def __str__(self):
        return "EquipmentConfig object with equipment_id = %s, updated at %s. Object is %s\n" % \
               (self.equipment_id_id, self.updated, self.equipment_id)

    class Meta:
        ordering = ('-updated', )


class EquipmentPorts(models.Model):
    up_down_choices = (('Up', 'up'), ('Down', 'down'))
    equipment_id = models.ForeignKey(Equipment, on_delete=models.CASCADE, null=True)  # Equipment foreign key
    if_alias = models.CharField(max_length=256, null=True, default=None)  # alias, eq "FastEthernet0/3"
    if_name = models.CharField(max_length=256, null=True, default=None)  # name, eq "Fa0/3"
    # description, eq "To AMTS Server NIC2 at 203 room"
    if_descr = models.CharField(max_length=512, null=True, default=None)
    if_oper_status = models.CharField(max_length=4, choices=up_down_choices)  # operational status, up or down
    if_admin_status = models.CharField(max_length=4, choices=up_down_choices)  # administrative status, up or down
    if_speed = models.BigIntegerField(default=0)  # interface speed
    if_ip = InetAddressField()

    objects = NetManager()


class Subnets(models.Model):
    network = InetAddressField(db_index=True, unique=True)
    descr = models.CharField(max_length=256, default='')
    is_active = models.BooleanField(default=True)

    objects = NetManager()

lna/users/views.py
from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

lna/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

lna/templates/base.html
{% load staticfiles i18n %}{% load argus.tags %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>LNA | {% block title %}lna{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-select.css' %}">
    <link rel="stylesheet" href="{% static 'css/font-awesome.css' %}">

    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/highlight.css' %}" rel="stylesheet">

    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">LNA</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item {% active_url 'home' %}">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item {% active_url 'about' %}">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
              {% if request.user.is_authenticated %}
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarArgusDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Техучет</a>
                      <div class="dropdown-menu" aria-labelledby="navbarArgusDropdown">
                          <a class="dropdown-item font-weight-bold {% active_url 'argus:search' %}" href="{% url 'argus:search' %}">Поиск клиента</a>
                          <a class="dropdown-item {% active_url 'argus:astu' %}" href="{% url 'argus:astu' %}">АСТУ</a>
                          <a class="dropdown-item disabled {% active_url 'argus:import' %}" href="{% url 'argus:import' %}">Import</a>
                          <a class="dropdown-item {% active_url 'net:ne_list' %}" href="{% url 'net:ne_list' %}">Discovered NE List</a>
                          <a class="dropdown-item {% active_url 'net:config_search' %}" href="{% url 'net:config_search' %}">Config Search</a>
                      </div>
                  </li>

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarTaskDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Tasks</a>
                      <div class="dropdown-menu" aria-labelledby="navbarTaskDropdown">
                          <a class="dropdown-item {% active_url 'net:pick_ne' %}" href="{% url 'net:pick_ne' %}">Выбор оборудования</a>
                          <a class="dropdown-item {% active_url 'net:active_tasks' %}" href="{% url 'net:active_tasks' %}">Активные задания</a>
                          <a class="dropdown-item {% active_url 'net:discover_subnets' %}" href="{% url 'net:discover_subnets' %}">Обнаружение в подсети</a>
                          <a class="dropdown-item {% active_url 'net:clients_count' %}" href="{% url 'net:clients_count' %}">Подсчёт кол-ва клиентов по узлам</a>
                          <a class="dropdown-item {% active_url 'net:cmd_runner' %}" href="{% url 'net:cmd_runner' %}">CMD runner</a>
                      </div>
                  </li>

                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarTaskDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Settings</a>
                    <div class="dropdown-menu" aria-labelledby="navbarTaskDropdown">
                        <a class="dropdown-item {% active_url 'net:subnets_list' %}" href="{% url 'net:subnets_list' %}">Subnets List</a>
                    </div>
                  </li>

                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarMiscDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Misc</a>
                      <div class="dropdown-menu" aria-labelledby="navbarMiscDropdown">
                          <a class="dropdown-item {% active_url 'net:demo' %}" href="{% url 'net:demo' %}">demo</a>
                          <a class="dropdown-item" href="http://10.179.9.55:5555/" target="_blank">Flower</a>
                          <a class="dropdown-item" href="/api/" target="_blank">DRF</a>
                          <a class="dropdown-item" href="/admin/" target="_blank">Admin</a>
                      </div>
                  </li>

              {% endif %}
          </ul>
          <ul class="navbar-nav masthead">
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link {% active_url 'users:detail' %}" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link {% active_url 'account_logout' %}" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link {% active_url 'account_signup' %}" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link {% active_url 'account_login' %}" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="{% if fluid_container is True %}container-fluid{% else %}container{% endif %}">
    <div id="js_messages"></div>
      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %} alert-dismissible fade show" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
                  {{ message }}
              </div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    <div id="js_messages_bottom"></div>

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      <!-- Required by Bootstrap v4 Alpha 4 -->
        <!--
      <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
      -->
        <script src="http://code.jquery.com/jquery-latest.js"></script>
        <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.js' %}"></script>
      <script src="{% static 'js/bootstrap-select.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->

      <!-- place project specific Javascript in this file -->
        <script src="{% static 'js/socket.io.js' %}"></script>
        <script src="{% static 'js/project.js' %}"></script>
        <script src="{% static 'js/multiselect.js' %}"></script>



    {% endblock javascript %}
  </body>
</html>