api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from api.views import NEViewSet, ListVendors, ListModels, ListTasks, NEDetail, ArchiveConfig, ConfigDiff, \
    IsPPPoEIAConfigured, ConfigSearch

router = routers.DefaultRouter()
router.register(r'ne_list', NEViewSet, 'ne_list')
router.register(r'vendors', ListVendors, 'vendors')
router.register(r'models', ListModels, 'models')
router.register(r'tasks', ListTasks, 'tasks')
# router.register(r'ne_detail', NEDetail, 'ne_detail')


urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'ne_detail/(?P<pk>[0-9]+)/$', NEDetail.as_view()),
    url(r'get_archived_config/(?P<pk>[0-9]+)/$', ArchiveConfig.as_view()),
    url(r'get_config_diff/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ConfigDiff.as_view()),
    url(r'is_pppoe_ia_configured/(?P<ip>.+)/$', IsPPPoEIAConfigured.as_view()),
    url(r'config_search/(?P<ip>.+)/(?P<search>.+)$', ConfigSearch.as_view()),
    url(r'^', include(router.urls))

]

argus/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from argus.views import ClientImport, ASTUView, SearchView

urlpatterns = [
    url(r'^import$', ClientImport.as_view(), name='import'),
    url(r'^astu$', ASTUView.as_view(), name='astu'),
    url(r'^find$', SearchView.as_view(), name='search'),

]

lna/users/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

argus/models.py
from django.db import models

# Create your models here.
class ArgusADSL(models.Model):
    city = models.CharField(max_length=512, default='N/A')
    hostname = models.CharField(max_length=512, default='None')
    ne_ip = models.GenericIPAddressField(protocol='IPv4', default='0.0.0.0')
    tel_num = models.CharField(default='', max_length=16, db_index=True)
    address = models.CharField(max_length=512, default='N/A')
    fio = models.CharField(max_length=512, default='N/A')
    room = models.CharField(max_length=512, default='N/A')
    iptv_login = models.CharField(max_length=512, db_index=True)
    inet_login = models.CharField(max_length=512, db_index=True)
    slot = models.CharField(max_length=512, default='N/A')
    port = models.CharField(max_length=512, default='N/A')
    lira = models.CharField(max_length=32, default='N/A')


class ArgusFTTx(models.Model):
    city = models.CharField(max_length=512, default='N/A')
    hostname = models.CharField(max_length=512, default='None')
    ne_ip = models.GenericIPAddressField(protocol='IPv4', default='0.0.0.0')
    tel_num = models.CharField(default='', max_length=16, db_index=True)
    address = models.CharField(max_length=512, default='N/A')
    fio = models.CharField(max_length=512, default='N/A')
    room = models.CharField(max_length=512, default='N/A')
    iptv_login = models.CharField(max_length=512, db_index=True)
    inet_login = models.CharField(max_length=512, db_index=True)
    slot = models.CharField(max_length=512, default='N/A')
    port = models.CharField(max_length=512, default='N/A')
    lira = models.CharField(max_length=32, default='N/A')


class ArgusGPON(models.Model):
    city = models.CharField(max_length=512, default='N/A')
    hostname = models.CharField(max_length=512, default='None')
    ne_ip = models.GenericIPAddressField(protocol='IPv4', default='0.0.0.0')
    tel_num = models.CharField(default='', max_length=16, db_index=True)
    address = models.CharField(max_length=512, default='N/A')
    fio = models.CharField(max_length=512, default='N/A')
    room = models.CharField(max_length=512, default='N/A')
    iptv_login = models.CharField(max_length=512, db_index=True)
    inet_login = models.CharField(max_length=512, db_index=True)
    slot = models.CharField(max_length=512, default='N/A')
    port = models.CharField(max_length=512, default='N/A')
    lira = models.CharField(max_length=32, default='N/A')


# Common client model
class Client(models.Model):
    city = models.CharField(max_length=512, default='N/A')
    hostname = models.CharField(max_length=512, default='None')
    ne_ip = models.GenericIPAddressField(protocol='IPv4', default='0.0.0.0')
    tel_num = models.CharField(default='', max_length=16, db_index=True)
    address = models.CharField(max_length=512, default='N/A')
    fio = models.CharField(max_length=512, default='N/A')
    room = models.CharField(max_length=512, default='N/A')
    iptv_login = models.CharField(max_length=512, db_index=True)
    inet_login = models.CharField(max_length=512, db_index=True)
    slot = models.CharField(max_length=512, default='N/A')
    port = models.CharField(max_length=512, default='N/A')
    lira = models.CharField(max_length=32, default='N/A')
    tech = models.CharField(max_length=32, default='N/A')


class ASTU(models.Model):
    hostname = models.CharField(max_length=512, default='', unique=True, db_index=True)
    address = models.CharField(max_length=512, default='')
    structure_level = models.CharField(max_length=512, default='')
    ne_class = models.CharField(max_length=512, default='')  # class is python reserved word
    vendor = models.CharField(max_length=512, default='')
    model = models.CharField(max_length=512, default='')
    status = models.CharField(max_length=512, default='')
    comment = models.CharField(max_length=512, default='')
    ne_ip = models.GenericIPAddressField(protocol='IPv4', db_index=True)
    category = models.CharField(max_length=16, default='')
    segment = models.CharField(max_length=512, default='')
    serial_number = models.CharField(max_length=512, default='')
    is_online = models.BooleanField(default=False)

    def __str__(self):
        return self.hostname + " : " + self.ne_ip + " : " + self.vendor + " : " + self.model

argus/forms.py
from django import forms
from argus.models import ASTU


class ArgusFileUploadForm(forms.Form):
    file = forms.FileField(required=True, label='Выберите файл')
    file.widget.attrs = {
        'class': 'custom-file',
        'accept': '.csv'
    }
    tech_choices = (('', ''), ('1', 'ADSL'), ('2', 'GPON'), ('3', 'FTTx'), ('4', 'АСТУ'))
    tech = forms.ChoiceField(widget=forms.Select(), choices=tech_choices, label='Выбор технологии', required=True)
    tech.widget.attrs = {
        'class': 'custom-select',

    }


class ArgusSearchForm(forms.Form):
    input_string = forms.CharField(widget=forms.TextInput, label='')
    input_string.widget.attrs = {
        'placeholder': 'Логин, телефон или ФИО',
        'class': 'form-control'
    }


class ASTUSearchForm(forms.Form):

    @staticmethod
    def get_some_tuples_from_ASTU(field_name, label):
        field_dict = dict()
        field_objects = ASTU.objects.order_by(field_name).distinct(field_name)
        field_dict[''] = label
        for obj in field_objects:
            field_dict[getattr(obj, field_name)] = getattr(obj, field_name)
        return tuple(field_dict.items())

    input_string = forms.CharField(widget=forms.TextInput, label='', required=False)
    input_string.widget.attrs = {
        'placeholder': 'hostname/ip/адрес',
        'class': 'form-control',
        'size': 13
    }

    # partyhard =)
    vendor = forms.ChoiceField(
        widget=forms.Select(),
        choices=get_some_tuples_from_ASTU.__func__('vendor', 'Производитель'),
        label='', required=False
    )
    model = forms.ChoiceField(
        widget=forms.Select(),
        choices=get_some_tuples_from_ASTU.__func__('model', 'Модель'),
        label='', required=False
    )
    segment = forms.ChoiceField(
        widget=forms.Select(),
        choices=get_some_tuples_from_ASTU.__func__('segment', 'Сегмент'),
        label='', required=False
    )
    status = forms.ChoiceField(
        widget=forms.Select(),
        choices=get_some_tuples_from_ASTU.__func__('status', 'Статус'),
        label='', required=False
    )

    status.widget.attrs = {'class': 'custom-select custom-select-sm'}
    model.widget.attrs = {'class': 'custom-select custom-select-sm'}
    vendor.widget.attrs = {'class': 'custom-select custom-select-sm'}
    segment.widget.attrs = {'class': 'custom-select custom-select-sm'}

    def __init__(self, *args, **kwargs):
        super(ASTUSearchForm, self).__init__(*args, **kwargs)
        self.initial['status'] = 'эксплуатация'

argus/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, UpdateView, ListView
from django.contrib import messages
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.db.models import Q
from django.shortcuts import render, HttpResponse, redirect
from el_pagination.views import AjaxListView
from el_pagination.decorators import page_template
from argus.models import ArgusADSL, ArgusFTTx, ArgusGPON, ASTU, Client
from argus.forms import ArgusFileUploadForm, ArgusSearchForm, ASTUSearchForm
from argus.argus_lib import parse_adsl_csv, parse_fttx_csv, parse_gpon_csv, parse_astu_csv, ip_pattern
import re


# Create your views here.
# Загрузка из CSV файла
class ClientImport(LoginRequiredMixin, TemplateView):
    template_name = 'argus/adsl.html'

    def get(self, request, *args, **kwargs):
        form = ArgusFileUploadForm()
        args = {'form': form}
        return render(request, self.template_name, args)

    def post(self, request):
        form = ArgusFileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            uploaded_file = request.FILES['file']
            fs = FileSystemStorage()
            filename = fs.save(uploaded_file.name, uploaded_file)
            file_path = fs.url(filename)
            messages.add_message(request, messages.INFO, 'File was uploaded to '+file_path)
            # Check tech | технология подключения
            tech = form.cleaned_data['tech']
            counter = '0'
            ignored = '0'
            if tech == '1':
                counter = parse_adsl_csv(file_path)
            elif tech == '2':
                counter, ignored = parse_gpon_csv(file_path)
            elif tech == '3':
                counter, ignored = parse_fttx_csv(file_path)
            elif tech == '4':
                counter, ignored = parse_astu_csv(file_path)
            else:
                messages.add_message(request, messages.ERROR, 'Выбрана непонятная технология включения')

            messages.add_message(request, messages.INFO,
                                 'Добавлено ' + str(counter) + ' записей. Проигнорировано - ' + str(ignored))
        else:
            messages.add_message(request, messages.ERROR, "Ошибка")
            messages.add_message(request, messages.ERROR, form.errors)
            pass

        # New Form
        form = ArgusFileUploadForm()
        args = {'form': form}
        return render(request, self.template_name, args)


# Lists NE from ASTU
class ASTUView(LoginRequiredMixin, FormView, ListView):
    context_object_name = 'astu_list'
    template_name = 'argus/astu.html'
    form_class = ASTUSearchForm
    success_url = '/argus/astu'
    model = ASTU

    def get_queryset(self):
        if self.request.method == 'POST':
            form = ASTUSearchForm(self.request.POST)
            if form.is_valid():
                input_string = form.cleaned_data['input_string']
                status = form.cleaned_data['status']
                vendor = form.cleaned_data['vendor']
                model = form.cleaned_data['model']
                segment = form.cleaned_data['segment']

                search_objects = ASTU.objects.all()

                if input_string:
                    if re.findall(ip_pattern, input_string):
                        search_objects = ASTU.objects.filter(ne_ip=input_string)
                    else:
                        search_objects = ASTU.objects.filter(
                            Q(hostname__icontains=input_string) |
                            Q(address__icontains=input_string)
                        )
                if status:
                    search_objects = search_objects.filter(status=status)
                if vendor:
                    search_objects = search_objects.filter(vendor=vendor)
                if model:
                    search_objects = search_objects.filter(model=model)
                if segment:
                    search_objects = search_objects.filter(segment=segment)
                return search_objects
            else:
                messages.add_message(self.request, messages.ERROR, form.errors)

        return ASTU.objects.all().filter(status__exact='эксплуатация')[:5]

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ASTUView, self).get_context_data(**kwargs)
        # context['fluid_container'] = True
        context['row_count'] = self.get_queryset().count() or 0
        return context


class SearchView(LoginRequiredMixin, AjaxListView, FormView):
    template_name = 'argus/search_view.html'
    form_class = ArgusSearchForm
    success_url = '/argus/find'
    page_template = 'argus/search_view_list_page.html'

    def get_queryset(self):
        return None

    # OMFG!!!
    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SearchView, self).get_context_data(**kwargs)
        context['page_template'] = self.page_template
        if self.request.method == 'POST':
            context['search'] = self.request.POST['input_string']
            context['results'] = self.get_results(self.request.POST['input_string'])
            context['form'] = ArgusSearchForm(self.request.POST)
        else:
            context['search'] = self.request.GET.get('search')
            context['results'] = self.get_results(self.request.GET.get('search'))
            context['form'] = ArgusSearchForm()
        context['fluid_container'] = True
        context['gpon_page'] = 'gpon_page'
        return context

    def get_results(self, input_string=None):
        search_objects = Client.objects.all().order_by('id')
        count = 15
        if input_string:
            if re.findall(ip_pattern, input_string):
                search_objects = search_objects.filter(ne_ip=input_string)
                count = search_objects.count()
            else:
                search_objects = search_objects.filter(
                    Q(inet_login__contains=input_string) |
                    Q(iptv_login__contains=input_string) |
                    Q(tel_num__contains=input_string) |
                    Q(address__icontains=input_string) |
                    Q(fio__icontains=input_string) |
                    Q(hostname__icontains=input_string)
                )
                count = search_objects.count()
            return {'search_objects': search_objects, 'count': count}
        return {'search_objects': search_objects[:15], 'count': count}

argus/templates/argus/adsl.html
{% extends 'base.html' %}

{% block title %}Загрузка данных из Аргус{% endblock %}


{% block content %}
    <h3>Загрузка данных из Аргус / АСТУ</h3>
    <div class="alert alert-danger alert-dismissible fade show">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        <strong>Внимание!</strong> Загруженный файл перепишет содержимое базы данных!
    </div>
    <p></p>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group row">
            <label class="col-sm-2 col-form-label" for="id_tech">{{ form.tech.label }}</label>
            {{ form.tech }}
        </div>
        <div class="form-group">
            <label class="custom-file">
                {{ form.file }}
                <span class="custom-file-control"></span>
            </label>
        </div>
        <button type="submit" class="btn btn-primary disabled">Загрузить</button>
        <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#csv_help_modal">Помощь</button>
    </form>
{% endblock %}

{% block modal %}
    <!-- Modal -->
<div class="modal fade bd-example-modal-lg" id="csv_help_modal" tabindex="-1" role="dialog" aria-labelledby="csv_help_modal" aria-hidden="true">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModal">Пример форматирования CSV-файла</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Якобы файл автоматически выгружается из Аргуса</p>
          <p>Пример ADSL:</p>
          <pre>ФЭС;Регион;Логич.устройство;IP;Основная услуга;Адрес;Клиент;Квартира;IPTV;ШПД;Порты xDSL(слот);Номер порта;
Ямало-Ненецкий;Ямало-Ненецкий АО, Губкинский г.;89-GBKNSK-EDG101-DSL-1[10.205.0.164];;(34936)30005;мкр 3-й, 23;Леготина М. С.;1;IP-TV Smart TUBE089004932;СПД893623347;Порты ADSL2+_AnnexA - 6;42
</pre>
          <p>Пример GPON</p>
          <pre>ФЭС;Регион;OLT;IP;Номер платы HPSA;Номер порта на плате HPSA;Сплиттер;Код ИП сплиттера;Регион сплиттера;Адрес сплиттера;Группа опт. портов;Номер порта;Цвет;№ ОРК;Код региона услуги;Услуга;Клиент;Регион установки;Адрес установки;Квартира;Номер наряда ЛИРА;ШПД;IP-TV;SIP/IMS;
Ямало-Ненецкий;Ямало-Ненецкий АО, Губкинский г.;89-GBKNSK-BB01-O1 Huawei(мкр 4-й, 25)[10.228.102.250];10.228.102.250;1;0;89-GBKNSK-BB01-O1 Huawei(мкр 4-й, 25)[10.228.102.250] - РО-1-0(1:8) - 6-20/1(1:8);';Ямало-Ненецкий АО, Губкинский г.;мкр 6-й, 20;оп-0-2;0;_красн;;34936;(34936)Порт13787;Харитон М. З.;Ямало-Ненецкий АО, Губкинский г.;мкр 6-й, 20;6;76664711;СПД893626931;IP-TV Smart TUBE089078420;</pre>
          <p>Пример FTTx</p>
          <pre>ФЭС;Регион;КД;Плата; Код ИП платы;Порт;Услуга;Наряд Лира;ШПД;IPTV;SIP/IMS;Клиент;Адрес;Квартира;Точка на КРТ;КРТ;Емкость КРТ;
Ямало-Ненецкий;Ямало-Ненецкий АО, Губкинский г.;89-GBKNSK-EDG147-SW-1[10.205.0.230];2  (Плата портов СПД);';_2;(34936)Порт11752;99461644;;;IMS29015;Акционерное общество "Партнер";ул Панель 4, 0;;;;</pre>
          <p>Пример АСТУ</p>
          <pre>Узел;Сетевое имя;Адрес;Структурный уровень;Класс;Производитель;Модель;Инвентарный номер;Статус;Количество свободных портов;Точка подключения;Комментарий;Адрес управления;Категория;Тип Wi-Fi;Последняя миля;Подключение к устройству; IP устройства подключения;Сегмент;Серийный номер;Дата ввода в эксплуатацию
89-PANGD-EDG104;89-PANGD-EDG104-DSL-3;пгт. Пангоды, ул. Мира, д.17, оф.;DSLAM;DSLAM;Alcatel;7302 FD;;эксплуатация;0;не опр.;1285283;10.205.12.168;A4;;; ; ;DSLAM;3FE26685AA;13.09.2011</pre>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-sm btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% endblock %}

argus/templates/argus/adsl_view.html
{% extends 'base.html' %}

{% block title %}Данные по {{ tech_in_title }}-портам{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group mx-sm-3">
                {{ form }}
            </div>
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>
        <h2>Данные из БД:</h2> {{ search }}
        <script type="application/javascript">
        {% if search %}

            var search_string = "{{ search }}";
            console.log('search string was set');

        {% else %}
            var search_string = '';
        {% endif %}
        </script>
        {% include page_template %}
    </div>
{% endblock %}

{% block javascript %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollChunkSize: 5
        });
    </script>
{% endblock %}

argus/templates/argus/adsl_view_list_page.html
{% load el_pagination_tags %}
<table class="table table-striped table-bordered table-hover table-sm">
    <thead>
    <tr>
        <th>Internet</th>
        <th>IPTV</th>
        <th>Город</th>
        <th>Улица, дом</th>
        <th>Квартира</th>
        <th>Телефон</th>
        <th>Ф.И.О.</th>
        <th>NE</th>
        <th>IP</th>
        <th>Слот</th>
        <th>Порт</th>
    </tr>
    </thead>
    <tbody>
    {% paginate argus_list %}
        {% for port in argus_list %}
            <tr>
                <td>{{ port.inet_login }}</td>
                <td>{{ port.iptv_login }}</td>
                <td>{{ port.city }}</td>
                <td>{{ port.address }}</td>
                <td>{{ port.room }}</td>
                <td>{{ port.tel_num }}</td>
                <td>{{ port.fio }}</td>
                <td>{{ port.hostname }}</td>
                <td>{{ port.ne_ip }}</td>
                <td>{{ port.slot }}</td>
                <td>{{ port.port }}</td>
            </tr>
        {% endfor %}
    </tbody>
</table>
    {% show_more %}

argus/templates/argus/astu.html
{% extends 'base.html' %}
{% load argus.tags %}

{% block title %}Данные из АСТУ{% endblock %}

{% block content %}
    <h1>Данные из АСТУ</h1>

    <form method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group mx-sm-3 form-inline">
                {{ form }}
            </div>
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>

    <p>Найдено: {{ row_count }}</p>
    {% if astu_list %}
        </div>
            <div class="container-fluid">
           <table class="table table-striped table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th>Hostname</th>
                    <th>IP</th>
                    <th>Производитель</th>
                    <th>Модель</th>
                    <th>Сегмент</th>
                    <th>Адрес</th>
                </tr>
                </thead>
                <tbody>

        {% for ne in astu_list %}
            <tr>
                <td>{{ ne.hostname }}{{ ne.status|status_badge }}
                {% if ne.is_online == True %}
                    <i class="fa fa-check text-success" title="online"></i>
                {% else %}
                    <i class="fa fa-times text-danger" title="offline"></i>
                {% endif %}
                </td>
                <td>{{ ne.ne_ip }}</td>
                <td>{{ ne.vendor }}</td>
                <td>{{ ne.model }}</td>
                <td>{{ ne.segment }}</td>
                <td>{{ ne.address }}</td>
            </tr>

        {% empty %}
            <p>Не найдено</p>
        {% endfor %}
                </tbody>
           </table>
        </div>
    {% endif %}

{% endblock %}

argus/templates/argus/search_view.html
{% extends 'base.html' %}

{% block title %}Данные по {{ tech_in_title }}-портам{% endblock %}

{% block content %}
    <div class="container-fluid">
        <form method="post" class="form-inline">
            {% csrf_token %}
            <div class="form-group mx-sm-3">
                {{ form }}
            </div>
            <button type="submit" class="btn btn-primary">Искать</button>
        </form>
        <h2>Данные из БД:</h2>
        <p> Запрос: <span class="bg-faded font-weight-bold">{{ search }}</span>. Найдено: {{ results.count }}</p>
        <script type="application/javascript">
        {% if search %}

            var search_string = "{{ search }}";
            console.log('search string was set');

        {% else %}
            var search_string = '';
        {% endif %}
        </script>
        <div class="endless_page_template">
            {% include "argus/search_view_list_page.html" %}
        </div>

    </div>
{% endblock %}


{% block javascript %}
    {{ block.super }}
    <script src="{{ STATIC_URL }}el-pagination/js/el-pagination.js"></script>
    <script>
        $.endlessPaginate({
            paginateOnScroll: true,
            paginateOnScrollChunkSize: 5
        });
    </script>
{% endblock %}

argus/templates/argus/search_view_list_page.html
{% load el_pagination_tags %}
<table class="table table-striped table-bordered table-hover table-sm">
    <thead>
    <tr>
        <th>Internet</th>
        <th>IPTV</th>
        <th>Город</th>
        <th>Улица, дом</th>
        <th>Квартира</th>
        <th>Телефон</th>
        <th>Ф.И.О.</th>
        <th>NE</th>
        <th>IP</th>
        <th>Слот</th>
        <th>Порт</th>
        <th>Tech</th>
    </tr>
    </thead>
    <tbody>
    {% paginate results.search_objects as ports %}
        {% for port in ports %}
            <tr>
                <td>{{ port.inet_login }}</td>
                <td>{{ port.iptv_login }}</td>
                <td>{{ port.city }}</td>
                <td>{{ port.address }}</td>
                <td>{{ port.room }}</td>
                <td>{{ port.tel_num }}</td>
                <td>{{ port.fio }}</td>
                <td>{{ port.hostname }}</td>
                <td>{{ port.ne_ip }}</td>
                <td>{{ port.slot }}</td>
                <td>{{ port.port }}</td>
                <td>{{ port.tech }}</td>
            </tr>
        {% endfor %}

    </tbody>
</table>
    {% show_more %}