api/urls.py
from django.conf.urls import include, url
from rest_framework import routers
from api.views import NEViewSet, ListVendors, ListModels, ListTasks, NEDetail, ArchiveConfig, ConfigDiff, \
    IsPPPoEIAConfigured, ConfigSearch

router = routers.DefaultRouter()
router.register(r'ne_list', NEViewSet, 'ne_list')
router.register(r'vendors', ListVendors, 'vendors')
router.register(r'models', ListModels, 'models')
router.register(r'tasks', ListTasks, 'tasks')
# router.register(r'ne_detail', NEDetail, 'ne_detail')


urlpatterns = [
    url(r'^api-auth/', include('rest_framework.urls')),
    url(r'ne_detail/(?P<pk>[0-9]+)/$', NEDetail.as_view()),
    url(r'get_archived_config/(?P<pk>[0-9]+)/$', ArchiveConfig.as_view()),
    url(r'get_config_diff/(?P<pk>[0-9]+)/(?P<pk2>[0-9]+)/$', ConfigDiff.as_view()),
    url(r'is_pppoe_ia_configured/(?P<ip>.+)/$', IsPPPoEIAConfigured.as_view()),
    url(r'config_search/(?P<ip>.+)/(?P<search>.+)$', ConfigSearch.as_view()),
    url(r'^', include(router.urls))

]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('lna.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go here
    url(r'^argus/', include('argus.urls', namespace='argus')),
    url(r'^net/', include('net.urls', namespace='net')),
    url(r'^api/', include('api.urls', namespace='drf')),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + \
static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

net/urls.py
from django.conf.urls import include, url
from net.views import Demo, PickNE, DoTask, ActiveTasks, ArchiveTasks, TaskDetail, DiscoverSubnets, ClientsCount, \
    NEList, NEDetail, SubnetsList, ConfigSearch, CMDRunner

urlpatterns = [
    url(r'^demo$', Demo.as_view(), name='demo'),
    url(r'^pick_ne', PickNE.as_view(), name='pick_ne'),
    url(r'^do_task', DoTask.as_view(), name='do_task'),
    url(r'^active_tasks', ActiveTasks.as_view(), name='active_tasks'),
    url(r'^archive_tasks', ArchiveTasks.as_view(), name='archive_tasks'),
    url(r'^task_detail/(?P<task_id>[0-9]+)/$', TaskDetail.as_view(), name='task_detail'),
    url(r'^discover_subnets$', DiscoverSubnets.as_view(), name='discover_subnets'),
    url(r'^clients_count$', ClientsCount.as_view(), name='clients_count'),
    url(r'^ne_list', NEList.as_view(), name='ne_list'),
    url(r'^ne_detail/(?P<pk>[0-9]+)/$', NEDetail.as_view(), name='ne_detail'),
    url(r'subnets', SubnetsList.as_view(), name='subnets_list'),
    url(r'config_search', ConfigSearch.as_view(), name='config_search'),
    url(r'cmd_runner', CMDRunner.as_view(), name='cmd_runner'),
]

net/forms.py
from django import forms
from net.models import Equipment


class TaskForm(forms.Form):
    task_status_choices = (('', ''), ('STARTED', 'STARTED'), ('SUCCESS', 'SUCCESS'),
                           ('IN PROGRESS', 'IN PROGRESS'), ('PENDING', 'PENDING'), ('ARCHIVED', 'ARCHIVED'),
                           ('TERMINATED', 'TERMINATED'))
    task_status = forms.ChoiceField(choices=task_status_choices, required=False, label='Выбрать статус задания')
    task_status.widget.attrs = {'class': 'custom-select', }


class ArchiveTasksForm(forms.Form):
    pass


class SubnetForm(forms.Form):
    subnets = forms.CharField(widget=forms.Textarea, required=False, label='')
    discover_task_choices = (('fping', 'Discover with FPING'), ('vendor', 'Discover Vendor and models'),
                             ('config', "Get Config from NE's"), ('put_syslocation', 'Put syslocation from ASTU'))
    subnets.widget.attrs = {
        'placeholder': "Enter the networks to scan with fping in CIDR format\n3 x /24 is OK.\n"
                       "For more network scan, please push checkbox \"send task to Celery\"\n"
                       "/24 scan took about 30 second, so /16 will be about 1/2 hour",
        'rows': 5,
        'cols': 40,
        'class': 'form-control',

    }
    cast_to_celery = forms.BooleanField(label='Send discovery task to Celery ', required=False)
    discover_task = forms.ChoiceField(choices=discover_task_choices, required=True, label='Choice task Type')
    discover_task.widget.attrs = {'class': 'custom-select', }


class NEListForm(forms.Form):
    ip_or_subnet = forms.CharField(widget=forms.TextInput, label='', required=False)
    ip_or_subnet.widget.attrs = {
        'placeholder': 'IP/Subnet/Hostname',
        'class': 'form-control m-1',
        # 'size': 15,
    }

    LOGIN_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
        ('any', "Don't care")
    ]
    is_login_discovered = forms.CharField(widget=forms.RadioSelect(choices=LOGIN_CHOICES),
                                          required=False, initial='no')

    VENDOR_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
        ('any', "Don't care")
    ]

    is_vendor_discovered = forms.CharField(widget=forms.RadioSelect(choices=VENDOR_CHOICES), required=False)


class ConfigSearchForm(forms.Form):
    search = forms.CharField(max_length=64, required=True, min_length=3)  # min 3 char for search
    search.widget.attrs = {
        'placeholder': 'Search term',
        'class': 'form-control',
    }


class CMDRunnerForm(forms.Form):
    ips_textfield = forms.CharField(widget=forms.Textarea, required=False, label='')
    ips_textfield.widget.attrs = {
        'placeholder': "Enter IP's of equipment or select NE vendor below",
        'class': 'form-control m-1',
        # 'size': 15,
    }
    distinct_objects = Equipment.objects.all().order_by('vendor').distinct('vendor').filter(vendor__isnull=False)
    vendor_choices_values_list = list()
    vendor_choices_values_list.append(('', ''))
    for obj in distinct_objects:
        vendor_choices_values_list.append(tuple((obj.vendor, obj.vendor)))
    vendor_choices_values = tuple(vendor_choices_values_list)
    vendor_choices = forms.ChoiceField(choices=vendor_choices_values, required=True,
                                       label='Run task for all NE from this vendor')
    vendor_choices.widget.attrs = {'class': 'custom-select', }
    commands_list = forms.CharField(widget=forms.Textarea, required=False, label='')
    commands_list.widget.attrs = {
        'placeholder': 'Commands to execute',
        'class': 'form-control m-1',
        'rows': 15,
    }

net/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import TemplateView, ListView, FormView, DetailView
from django.core.exceptions import PermissionDenied
from net.models import Scripts, Job, Equipment, Subnets, EquipmentConfig
from net.forms import TaskForm, ArchiveTasksForm, SubnetForm, NEListForm, ConfigSearchForm, CMDRunnerForm
from django.contrib import messages
from net.equipment.generic import GenericEquipment
from net.lib import celery_job_starter, scan_nets_with_fping, discover_vendor, cmd_to_celery
from argus.models import Client, ASTU
import re


# Create your views here.
class Demo(LoginRequiredMixin, TemplateView):
    template_name = 'net/demo.html'

    def get(self, request, *args, **kwargs):
        eq_device = Equipment.objects.get(ne_ip='10.205.18.247')  # equipment object
        eq = GenericEquipment(eq_device)
        eq.set_io_timeout(1)
        eq.suggest_login(resuggest=False)
        eq.do_login()
        eq.discover_vendor()
        return render(request, self.template_name, *args, **kwargs)


class PickNE(LoginRequiredMixin, TemplateView):
    template_name = 'net/pick_ne.html'

    def get_context_data(self, **kwargs):
        context = super(PickNE, self).get_context_data(**kwargs)
        possible_scripts = Scripts.objects.all().exclude(is_hidden=True)
        context['possible_scripts'] = possible_scripts
        return context


class DoTask(LoginRequiredMixin, TemplateView):
    template_name = 'net/do_task.html'

    def get(self, *args, **kwargs):
        raise PermissionDenied

    def post(self, request):
        """
        Нужно запустить стартер, который получит на вход список ID назначений, имя скрипта для выполнения, и возможно,
        какие-то дополнительные аргументы.

        :param request:

        :return:
        """
        destinations_ids = request.POST.getlist('destinations')
        script_id = request.POST['script_select']
        celery_job_starter(destinations_ids, script_id)
        args = dict()
        return render(request, self.template_name, args)


class ActiveTasks(LoginRequiredMixin, ListView, FormView):
    model = Job
    template_name = 'net/active_tasks.html'
    form_class = TaskForm
    paginate_by = 9
    success_url = '/net/active_tasks'

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        if self.request.method == 'POST':
            form = TaskForm(self.request.POST)
            if form.is_valid():
                task_status = form.cleaned_data['task_status']
                if task_status != '':
                    return Job.objects.filter(status=task_status)
                return Job.objects.all().exclude(status='ARCHIVED').exclude(status='TERMINATED')
        if self.request.method == 'GET':
            if self.request.GET.get('task_status') and (self.request.GET.get('task_status') != 'None'):
                return Job.objects.filter(status=self.request.GET.get('task_status'))
        return Job.objects.all().exclude(status='ARCHIVED').exclude(status='TERMINATED')

    def get_context_data(self, **kwargs):
        context = super(ActiveTasks, self).get_context_data(**kwargs)
        task_status = None
        if self.request.method == 'POST':
            form = TaskForm(self.request.POST)
            if form.is_valid():
                task_status = form.cleaned_data['task_status']
        if self.request.method == 'GET':
            task_status = self.request.GET.get('task_status')
        context['task_status'] = task_status
        return context


class ArchiveTasks(LoginRequiredMixin, FormView):
    template_name = 'net/archive_tasks.html'
    form_class = ArchiveTasksForm

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ArchiveTasks, self).get_context_data(**kwargs)
        if self.request.method == 'POST':
            Job.objects.filter(status='SUCCESS').update(status='ARCHIVED')
            messages.add_message(self.request, messages.INFO, 'Архивация выполена')
        return context


class TaskDetail(LoginRequiredMixin, TemplateView):
    template_name = 'net/task_detail.html'


class DiscoverSubnets(LoginRequiredMixin, FormView):
    template_name = 'net/discover_subnets.html'
    form_class = SubnetForm

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(DiscoverSubnets, self).get_context_data(**kwargs)
        context['new'] = False
        context['found'] = False
        if self.request.method == 'POST':
            form = SubnetForm(self.request.POST)
            if form.is_valid():
                subnets = form.cleaned_data['subnets'].split("\r\n")  # lists with subnet
                cast_to_celery = form.cleaned_data['cast_to_celery']  # "Send discovery task to Celery" checkbox
                discover_task = form.cleaned_data['discover_task']  # Task type
                context['cast_to_celery'] = cast_to_celery
                if discover_task == 'fping':
                    if not cast_to_celery:
                        found, new = scan_nets_with_fping(subnets)
                        context['found'] = found
                        context['new'] = new
                    else:
                        celery_job_starter(subnets, '999')  # 999 will be send task to celery for subnets scan
                if discover_task == 'vendor':
                    if not cast_to_celery:
                        discover_vendor(subnets)
                    else:
                        celery_job_starter(subnets, '1000')
                    pass
                if discover_task == 'config':
                    if not cast_to_celery:
                        # discover_config(subnets)
                        pass
                    else:
                        celery_job_starter(subnets, '1001')
                    pass
                if discover_task == 'put_syslocation':
                    if not cast_to_celery:
                        # only in celery
                        pass
                    else:
                        celery_job_starter(subnets, '1002')
        return context


class ClientsCount(LoginRequiredMixin, TemplateView):
    template_name = 'net/clients_count.html'

    def get_context_data(self, **kwargs):
        result_dict = dict()

        clients = Client.objects.all()
        for client in clients:
            hostname = client.hostname
            hostname_parts = hostname.split('-')
            try:
                node_name = hostname_parts[0] + '-' + hostname_parts[1] + '-' + hostname_parts[2]
                if node_name in result_dict:
                    result_dict[node_name] += 1
                else:
                    result_dict[node_name] = 1
            except IndexError:
                # skip
                # print(hostname)
                pass

        result_str = ''
        for node in result_dict:
            try:
                astu_objects = ASTU.objects.filter(hostname__contains=node).filter(status='эксплуатация')
                astu_first_object = astu_objects[0]
                address = astu_first_object.address
            except IndexError:
                address = 'Unknown'
            # print(node + ';' + str(result_dict[node]) + ';"' + address + '"')
            result_str += node + ';' + str(result_dict[node]) + ';"' + address + '"' + "\n"
        context = super(ClientsCount, self).get_context_data(**kwargs)
        context['result_str'] = result_str
        return context


class NEList(LoginRequiredMixin, ListView, FormView):
    template_name = 'net/ne_list.html'
    form_class = NEListForm
    model = Equipment
    success_url = 'net/ne_list'
    paginate_by = 20
    context_object_name = 'ne_list'

    def post(self, request, *args, **kwargs):
        return self.get(request, *args, **kwargs)

    def get_queryset(self):
        ne_list = Equipment.objects.all()

        # defaults
        is_login_discovered = 'any'  # any value
        is_vendor_discovered = 'any'
        ip_or_subnet = ''

        if self.request.method == 'POST':
            form = NEListForm(self.request.POST)
            if form.is_valid():
                is_login_discovered = form.cleaned_data['is_login_discovered']
                is_vendor_discovered = form.cleaned_data['is_vendor_discovered']
                ip_or_subnet = form.cleaned_data['ip_or_subnet']

        if self.request.method == 'GET':
            is_login_discovered = self.request.GET.get('is_login_discovered')
            is_vendor_discovered = self.request.GET.get('is_login_discovered')
            ip_or_subnet = self.request.GET.get('ip_or_subnet')

        # Filter login_discovered
        if is_login_discovered == 'yes':
            ne_list = ne_list.filter(credentials_id__isnull=False)
        elif is_login_discovered == 'no':
            ne_list = ne_list.filter(credentials_id__isnull=True)
        else:  # 'any'
            pass

        # Filter vendor discovered
        if is_vendor_discovered == 'yes':
            ne_list = ne_list.filter(vendor__isnull=False)
        elif is_vendor_discovered == 'no':
            ne_list = ne_list.filter(vendor__isnull=True)
        else:  # any
            pass

        ip_re = r'^([0-9]+\.){3}[0-9]+$'
        mask_re = r'^([0-9]+\.){3}[0-9]+\/\d{1,2}$'
        # IP / hostname / subnet filtering
        if ip_or_subnet and (ip_or_subnet is not None) and (ip_or_subnet != 'None'):
            if re.match(ip_re, ip_or_subnet):  # IP-address only
                ne_list = ne_list.filter(ne_ip=ip_or_subnet)
            elif re.match(mask_re, ip_or_subnet):  # Subnet
                try:

net/templates/net/archive_tasks.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}Архивация старых заданий{% endblock %}

{% block content %}
    <form method="post">
    {% csrf_token %}
    <p>Вы действительно хотите заархивировать старые задачи и их результаты?</p>
    <button type="submit" class="btn btn-warning">Заархивировать</button>
    </form>
    <br>
    <br>
    <p>Вернуться к списку задач?</p>
    <a class="btn btn-primary" href="{% url 'net:active_tasks' %}">Вернуться</a>
{% endblock %}

net/templates/net/config_search.html
{% extends 'base.html' %}
{% load staticfiles i18n %}{% load net.tags %}

{% block title %}Config Search{% endblock %}

{% block content %}
    <h1>Search string in actual NE configs</h1>
    <form method="post" action="/net/config_search">
    {% csrf_token %}
        <div class="form-group mx-sm-3 m-1">
            <label for="id_search">Search:</label>
            <input type="text" name="search" value="{{ search }}" placeholder="Search term" class="form-control" required id="id_search" />
            <button type="submit" class="btn btn-primary">Search</button>
        </div>

    </form>

    {% if row_count %}
    <p>Найдено: {{ row_count }}.</p>
    {% endif %}

    {% if ne_list %}
        </div>
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-auto">Hostname</div>
                <div class="col">IP</div>
                <div class="col">Vendor</div>
                <div class="col">Model</div>
                <div class="col-6">Config</div>
            </div>
        {% for ne in ne_list %}
            <div class="row">
            <div class="col-md-auto">
                {{ ne.hostname }}
                <a href="{% url 'net:ne_detail' pk=ne.id %}"><i class="fa fa-pencil fa-fw" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>
            </div>
            <div class="col">{{ ne.ne_ip|slice:":-3"|cut:"/32" }}</div>
            <div class="col">{{ ne.vendor }}</div>
            <div class="col">{{ ne.model }}</div>
            <div class="col-6">{{ ne.current_config|config_search:search }}</div>
            </div>
        {% empty %}
            <p>Не найдено</p>
        {% endfor %}
        </div>
    {% endif %}

    {% if is_paginated %}
        <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}&search={{ search }}" class="page-link">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                    <li class="page-item"><a href="?page={{ i }}&search={{ search }}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}&search={{ search }}" class="page-link">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        </nav>
    {% endif %}

{% endblock %}

net/templates/net/do_task.html
{% extends 'base.html' %}
{% block title %}Задания{% endblock %}
{% block content %}
    <h3>Запущено задание:</h3>
    <p>{{ script_name }} ({{ script_descr }}) (класс: {{ class_name }})</p>
    <h3>На следующем оборудовании:</h3>
    <dl class="row">
    {% for ne in ne_list %}
        <dt class="col-sm-6"> {{ ne.hostname }}({{ ne.ne_ip }})</dt><dd class="col-sm-6"> {{ ne.vendor }} {{ ne.model }}</dd>
    {% endfor %}
    </dl>
    <br><br>
    <h4><a href="{% url 'net:active_tasks' %}">Активные задания</a></h4>


{% endblock %}

net/templates/net/ne_list.html
{% extends 'base.html' %}
{% load staticfiles i18n %}

{% block title %}Discovered NE List{% endblock %}

{% block content %}
    <h1>Discovered NE List</h1>
    <form method="post" class="form-inline">
        {% csrf_token %}
        <input type="hidden" name="login_discovered_from_server" value="{{ is_login_discovered }}" id="login_discovered_from_server">
        <input type="hidden" name="vendor_discovered_from_server" value="{{ is_vendor_discovered }}" id="vendor_discovered_from_server">
        <input type="hidden" name="ip_or_subnet" value="{{ ip_or_subnet }}" id="ip_or_subnet_from_server">
        <div class="form-group mx-sm-3 m-1">
            {{ form.ip_or_subnet }}
            <div class="card text-center">
                <div class="card-header p-1">Login discovered?</div>
                <div class="btn-group card-block p-1 text-center" data-toggle="buttons" id="login_selected_group">
                    {% for log_el in form.is_login_discovered %}
                        <label for="{{ log_el.id_for_label }}" class="btn btn-outline-primary btn-sm">
                        {{ log_el.choice_label }}
                        {{ log_el.tag }}
                        </label>
                    {% endfor %}
                </div>
            </div>
            <div class="card text-center">
                <div class="card-header p-1">Vendor discovered?</div>
                <div class="btn-group card-block p-1 btn-group-sm" data-toggle="buttons">
                    {% for vendor_el in form.is_vendor_discovered %}
                        <label for="{{ vendor_el.id_for_label }}" class="btn btn-outline-primary btn-sm">
                        {{ vendor_el.choice_label }}
                        {{ vendor_el.tag }}
                        </label>
                    {% endfor %}
                </div>
            </div>
        </div>


        <button type="submit" class="btn btn-primary">Search</button>
    </form>

<p>Найдено: {{ row_count }}.</p>
<!-- <p>Login_var: {{ is_login_discovered }}. Vendor var: {{ is_vendor_discovered }} Search: {{ ip_or_subnet }}</p> -->
    {% if ne_list %}
        </div>
            <div class="container-fluid">
           <table class="table table-striped table-bordered table-hover table-sm">
                <thead>
                <tr>
                    <th>Hostname</th>
                    <th>IP</th>
                    <th>Vendor</th>
                    <th>Model</th>
                    <th>SW Ver</th>
                    <th>Login/pass</th>
                </tr>
                </thead>
                <tbody>

        {% for ne in ne_list %}
            <tr>
                <td>
                    {{ ne.hostname }}
                    {% if ne.telnet_port_open %}
                        <i class="fa fa-check-circle text-success" data-toggle="tooltip" data-placement="top" title="Telnet port is open"></i>
                    {% else %}
                        <i class="fa fa-times text-danger" data-toggle="tooltip" data-placement="top" title="Telnet port is closed"></i>
                    {% endif %}
                    <a href="{% url 'net:ne_detail' pk=ne.id %}"><i class="fa fa-pencil fa-fw" data-toggle="tooltip" data-placement="top" title="Edit"></i></a>
                </td>
                <td>{{ ne.ne_ip|slice:":-3"|cut:"/32" }}</td>
                <td>{{ ne.vendor }}</td>
                <td>{{ ne.model }}</td>
                <td>{{ ne.sw_version }}</td>
                <td>{{ ne.credentials_id }}</td>
            </tr>

        {% empty %}
            <p>Не найдено</p>
        {% endfor %}
                </tbody>
           </table>
        </div>
    {% endif %}


    {% if is_paginated %}
        <nav>
        <ul class="pagination">
            {% if page_obj.has_previous %}
                <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}&is_login_discovered={{ is_login_discovered }}&is_vendor_discovered={{ is_vendor_discovered }}&ip_or_subnet={{ ip_or_subnet }}" class="page-link">&laquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
            {% endif %}
            {% for i in paginator.page_range %}
                {% if page_obj.number == i %}
                    <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                {% elif i > page_obj.number|add:'-3' and i < page_obj.number|add:'3' %}
                    <li class="page-item"><a href="?page={{ i }}&is_login_discovered={{ is_login_discovered }}&is_vendor_discovered={{ is_vendor_discovered }}&ip_or_subnet={{ ip_or_subnet }}" class="page-link">{{ i }}</a></li>
                {% endif %}
            {% endfor %}
            {% if page_obj.has_next %}
                <li class="page-item"><a href="?page={{ page_obj.next_page_number }}&is_login_discovered={{ is_login_discovered }}&is_vendor_discovered={{ is_vendor_discovered }}&ip_or_subnet={{ ip_or_subnet }}" class="page-link">&raquo;</a></li>
            {% else %}
                <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
            {% endif %}
        </ul>
        </nav>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script src="{% static 'js/popper.js' %}"></script>
    {{ block.super }}
    <script>
    // tooltip initialization
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    });
    // according to https://getbootstrap.com/docs/4.0/components/buttons/#checkbox-and-radio-buttons
    // we need JS to set button-groups radios checked

    var is_login_discovered = $('#login_discovered_from_server').val();
    var is_vendor_discovered = $('#vendor_discovered_from_server').val();
    var ip_or_subnet = $('#ip_or_subnet_from_server').val();

    if (ip_or_subnet !== '' && ip_or_subnet !== 'None') {
        $('#id_ip_or_subnet').val(ip_or_subnet)
    }

    switch (is_login_discovered) {
        case 'yes':
            $('#id_is_login_discovered_0').prop('checked', 'true');
            $('label[for="id_is_login_discovered_0"]').addClass('active');
            break;
        case 'no':
            $('#id_is_login_discovered_1').prop('checked', 'true');
            $('label[for="id_is_login_discovered_1"]').addClass('active');

            break;
        case 'any':
            $('#id_is_login_discovered_2').prop('checked', 'true');
            $('label[for="id_is_login_discovered_2"]').addClass('active');
            break;
        default: // Don't care
            $('#id_is_login_discovered_2').prop('checked', 'true');
            $('label[for="id_is_login_discovered_2"]').addClass('active');
            break;
    }

    switch (is_vendor_discovered) {
        case 'yes':
            $('#id_is_vendor_discovered_0').prop('checked', 'true');
            $('label[for="id_is_vendor_discovered_0"]').addClass('active');
            break;
        case 'no':
            $('#id_is_vendor_discovered_1').prop('checked', 'true');
            $('label[for="id_is_vendor_discovered_1"]').addClass('active');

            break;
        case 'any':
            $('#id_is_vendor_discovered_2').prop('checked', 'true');
            $('label[for="id_is_vendor_discovered_2"]').addClass('active');
            break;
        default: // Don't care
            $('#id_is_vendor_discovered_2').prop('checked', 'true');
            $('label[for="id_is_vendor_discovered_2"]').addClass('active');
            break;
    }

    </script>

{% endblock %}